### ISSUE TITLE
'CSRF verification failed' when trying to login

### ISSUE THREAD

**Issue by paulgit** [galexrt/docker-healthchecks#14]
Hi, I have tried to test your docker image on two systems now, but each time I try to log in I get the following error in my browser

> Forbidden (403)
> CSRF verification failed. Request aborted.

Do you have any idea what the problem is?

**Comment by galexrt** [comment]
@paulgit Could you please provide information on how you run the docker image?

Following information would be good:
* Docker version
* Which image is used (hash)
* Environment variables given in the `docker run` command

**Comment by paulgit** [comment]
Sorry, I should have sent that in my original post! 

- Docker version 1.13.1, build 092cba3
- Image sha256:f053f35668022c5c89e0566451e8b5e4e3f8bb3b0d16e7357cd10e2356994398
- Environment variables as follows:
```
docker run \
    -d \
    --name=healthchecks \
    -p 80:8000 \
    -e 'HC_HOST=0.0.0.0' \
    -e 'HC_SECRET_KEY={removed}' \
    -e 'HC_PING_EMAIL_DOMAIN=mydomain.com' \
    -e 'HC_SITE_ROOT=http://mydomain.com' \
    -e 'HC_EMAIL_HOST={removed}' \
    -e 'HC_EMAIL_PORT=25' \
    -e 'HC_EMAIL_USE_TLS=True' \
    -e 'HC_EMAIL_HOST_USER={removed}' \
    -e 'HC_EMAIL_HOST_PASSWORD={removed}' \
    -e 'HC_ALLOWED_HOSTS=["*"]' \
    galexrt/healthchecks:latest
```

I am trying to run this on Ubuntu 16.04.4

**Comment by paulgit** [comment]
I have also just installed the latest docker and get the same error

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:17:40 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:16:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by paulgit** [comment]
Some further information, if I use your 'dev' version of the docker image I can log in ok

**Comment by galexrt** [comment]
@paulgit The problem is that Healthchecks needs to be run behind https (with proxy protocol headers passed through).
The cookies for CSRF verification are only allowed to be sent through securely through https.

So to make healthchecks work, you need to put a https proxy in front of it.
An example on how to do that is https://github.com/jwilder/nginx-proxy.
I will add a note to the README that https is required.
