### ISSUE TITLE
[Question] How to change logo placeholder

### ISSUE THREAD

**Issue by Kikobeats** [galexrt/docker-healthchecks#22]
Hello,

Thanks for this image, it's very useful 🙂

I didn't see a way for changing the default logo placeholder; I searched inside healthchecks repository without success.

Any idea how to do that?

**Comment by galexrt** [comment]
@Kikobeats You would need to mount a png file as a volume over the logo image.
Which would be located at `/healthchecks/static/img/logo-full.png` inside the container / image.

See https://github.com/healthchecks/healthchecks/blob/master/static/img/logo-full.png

**Comment by Kikobeats** [comment]
hum, why not use a Docker env variable?

**Comment by galexrt** [comment]
@Kikobeats Because healthchecks doesn't have an env var for the logo path.

**Comment by Kikobeats** [comment]
👍 thanks for reply 🙂
