### ISSUE TITLE
Receiving Emails

### ISSUE THREAD

**Issue by msebald** [galexrt/docker-healthchecks#29]
Hi,

how can I start the smtp daemon described [here](https://github.com/healthchecks/healthchecks#receiving-emails) inside the docker container?

I tried the following:
_docker exec -it containerid python3 /healthchecks/manage.py smtpd --port 2525_
This worked, but my command prompt was stuck and Ctrl-C terminates the smtp daemon.

Then I tried it in docker-compose.yml:
_command: python3 /healthchecks/manage.py smtpd --port 2525_
Then Healthchecks did not start anymore. Which is (maybe) because I am using a new startup command now (I am not a Docker expert).

Maybe you have a hint for me,
thank you,
Martin

**Comment by galexrt** [comment]
@msebald I have pushed https://github.com/galexrt/docker-healthchecks/commit/3b119e6beca2043d46cd5bc1189e54f3073de4c9 to implement that the smtpd service will be automatically start.

In a few minutes the following Docker image tag `v1.15.0-20200620-143251-752` will be available containing this change.

**Comment by msebald** [comment]
@galexrt Thank you for the quick fix/update. Works! :-) I will close the issue now. Thank you again!
