### ISSUE TITLE
Healthcheck not working with ALLOWED_HOSTS

### ISSUE THREAD

**Issue by samuel-p** [galexrt/docker-healthchecks#31]
The [`HEALTHCHECK`](https://github.com/galexrt/docker-healthchecks/blob/master/Dockerfile#L37) does not work if you set the `ALLOWED_HOSTS` environment variable.

If set calling http://localhost:8000 will result in a `400 Bad Resuest` and the container won't start. removing `ALLOWED_HOSTS` from environment fixes it, but is not permanent solution in my opinion.

**Comment by galexrt** [comment]
@samuel-p Can you check what happens if you add `localhost` to the `ALLOWED_HOSTS` list?

**Comment by samuel-p** [comment]
@galexrt yes, if I add `localhost` to the `ALLOWED_HOSTS` list, it works.

**Comment by galexrt** [comment]
@samuel-p Do you see that as a valid solution to add `localhost` to the examples, etc, to include `localhost` by default?

**Comment by samuel-p** [comment]
For me it's a valid solution, but I think it would be important to add a small note to the setup docs, if someone else has the same problem.

**Comment by galexrt** [comment]
@samuel-p I have updated the README and examples to have `localhost` included in the examples + added a note to the `ALLOWED_HOSTS` var description table.

Resolved by 6681abc607d4d1003a9d00a05ece3b80a71ccd87.
