### ISSUE TITLE
Using settelegramwebhook Doesn't Appear to Work

### ISSUE THREAD

**Issue by jimmybrancaccio** [galexrt/docker-healthchecks#32]
I may have had this working previously, but I can't remember. Nonetheless I setup a new Telegram bot, and setup the `TELEGRAM_BOT_NAME` and `TELEGRAM_TOKEN` environment variables. Then I used the manage.py command as noted in the docs, but get the following:

```
$ docker exec -it healthchecks /entrypoint.sh app:managepy settelegramwebhook

Running manage.py ...
/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults
  warnings.warn("local_settings.py not found, using defaults")
Fail: status=404, b'{"ok":false,"error_code":404,"description":"Not Found"}'
```

I'm not positive what it's 404'ing on. I do know that `local_settings.py` does not exist though, at least not in `/healthchecks/hc/`:

```
healthchecks@healthchecks:/healthchecks/hc $ ls -la
total 80
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 .
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 ..
-rw-r--r-- 1 healthchecks healthchecks    0 Jun 23 15:52 __init__.py
drwxr-xr-x 2 healthchecks healthchecks 4096 Jul  7 09:27 __pycache__
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 accounts
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 api
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 front
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 lib
-rw-r--r-- 1 healthchecks healthchecks  921 Jun 23 15:52 local_settings.py.example
drwxr-xr-x 1 healthchecks healthchecks 4096 Jul  7 09:27 payments
-rwxr-xr-x 1 healthchecks healthchecks 7197 Jun 23 15:52 settings.py
-rw-r--r-- 1 healthchecks healthchecks 1841 Jun 23 15:52 test.py
-rw-r--r-- 1 healthchecks healthchecks  732 Jun 23 15:52 urls.py
-rw-r--r-- 1 healthchecks healthchecks  381 Jun 23 15:52 wsgi.py
```

Here's the image information:

```
$ docker images |grep health
galexrt/healthchecks                                latest              0594ed8dd6b2        13 days ago         629MB
```

Any ideas?

**Comment by galexrt** [comment]
@jimmybrancaccio Not really. Make sure you have followed https://github.com/healthchecks/healthchecks#telegram.

Also have you tried setting `DEBUG: "true"` as an env variable to see if there is any debug output?

Otherwise maybe check with the healthchecks/healthchecks project issue list / board and / or create an issue there about the 404 error.

**Comment by jimmybrancaccio** [comment]
Hey, sorry about the delay in getting back to you on this issue. Busy week! That said, it looks like an issue with the Healthchecks code, probably in `hc/api/management/commands/settelegramwebhook.py`.

Running a cURL command from the container allows it to work:

```
curl -F “url=https://<YOURDOMAIN.EXAMPLE>/<WEBHOOKLOCATION>" https://api.telegram.org/bot<YOURTOKEN>/setWebhook
```

I'll get an issue created on their GitHub repo.

**Comment by galexrt** [comment]
@jimmybrancaccio Thanks for getting back to me and creating the upstream issue!

Feel free to mention and / or comment the upstream issue here.

**Comment by jimmybrancaccio** [comment]
Hey @galexrt, yes absolutely. I meant to do that but I got sidetracked by a zillion other things haha

https://github.com/healthchecks/healthchecks/issues/400

**Comment by jimmybrancaccio** [comment]
Alright, so I think it was something in #19 that caused me to setup the ENV variable for my Telegram token as such:

`HC_TELEGRAM_TOKEN=""123456789:AGHJDGHJD_HJAKJH8987dKJHKbb""`

which didn't work, so I just removed the double double quotes:

`HC_TELEGRAM_TOKEN=123456789:AGHJDGHJD_HJAKJH8987dKJHKbb`

and re-reran the command and it worked fine at that point:

```
~ $ docker exec -it healthchecks /entrypoint.sh app:managepy settelegramwebhook

Running manage.py ...
/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults
  warnings.warn("local_settings.py not found, using defaults")
Done, Telegram's webhook set to: https://healthchecks.linuxbox.ninja/integrations/telegram/bot/
```

So unless if I did the ENV variable wrong, we can consider this one a case closed.

**Comment by galexrt** [comment]
@jimmybrancaccio Right, the env vars don't `HC_` in front of them anymore as the `healthchecks` settings files now check the env vars for their vars.

**Comment by jimmybrancaccio** [comment]
@galexrt Ah my apologies, that was my `.env` output, not what I was actually sending too the container. My `docker-compose.yml` has:

```yaml
- TELEGRAM_BOT_NAME=${HC_TELEGRAM_BOT_NAME}
- TELEGRAM_TOKEN=${HC_TELEGRAM_TOKEN}
```

and my `.env` file now has (without the double double quotes):

```
HC_TELEGRAM_BOT_NAME=MyBot
HC_TELEGRAM_TOKEN=123456789:AGHJDGHJD_HJAKJH8987dKJHKbb
```

**Comment by galexrt** [comment]
@jimmybrancaccio So the issue is not resolved with using the env vars in the container without the `HC_` prefix?

**Comment by jimmybrancaccio** [comment]
No, it is resolved, I just wanted to clarify I wasn't sending environment variables with the `HC_` prefix 😝 I just use the `HC_` prefix in my `.env` file to help differentiate everything else I have in the `.env` file.

**Comment by galexrt** [comment]
Go it, thanks for clarifying!
