### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by CodeSmolder** [galexrt/docker-healthchecks#39]
Hi,

how can I set a my custom Logo in the upper left corner of the application?

<img width="504" alt="image" src="https://user-images.githubusercontent.com/37299230/94927820-160cbf00-04c3-11eb-8abb-0224619b1c00.png">

Is there a good way to do this without changing the Dockerfile?

**Comment by galexrt** [comment]
As was answered in #22 there is no option in the healthchecks/healthchecks project to change the logo image / url "on the fly" by env var or so.

See https://github.com/healthchecks/healthchecks/issues/323.
