### ISSUE TITLE
Image issues - Please Support

### ISSUE THREAD

**Issue by Rustymage** [galexrt/docker-healthchecks#40]
Hi All,

I'm having issues with a self hosted version of the software.

Details of the version I'm having issues with and the log I have showing what I hope is the reason...

ID | sha256:75eff274f174951708cb86a4c5e4fbe75e0c454a4a968b6b44b5506171f039ce 
Size | 631.1 MB
Created | 2020-09-02 19:32:02
Build | Docker 19.03.8 on linux, amd64

I'm not getting this issue with the previous build, dated 11th April 2020.

```
/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults

  warnings.warn("local_settings.py not found, using defaults")

Compressing... done

Compressed 20 block(s) from 104 template(s) for 0 context(s).

/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults

  warnings.warn("local_settings.py not found, using defaults")



You have requested to collect static files at the destination

location as specified in your settings:



    /healthchecks/static-collected



This will overwrite existing files!

Are you sure you want to do this?



Type 'yes' to continue, or 'no' to cancel: 

0 static files copied to '/healthchecks/static-collected', 314 unmodified.

Correcting config file permissions ...

Migrating database ...

/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults

  warnings.warn("local_settings.py not found, using defaults")

Operations to perform:

  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions

Running migrations:

  No migrations to apply.

Error: Format string '/scripts/prunepings.sh %(ENV_CONTAINER_PRUNE_INTERVAL)s' for 'program:prunepings.command' contains names ('ENV_CONTAINER_PRUNE_INTERVAL') which cannot be expanded. Available names: ENV_DATA_DIR, ENV_DEBIAN_FRONTEND, ENV_DEBUG, ENV_HC_EMAIL_HOST, ENV_HC_EMAIL_HOST_PASSWORD, ENV_HC_EMAIL_HOST_USER, ENV_HC_EMAIL_PORT, ENV_HC_EMAIL_USE_TLS, ENV_HC_REGISTRATION_OPEN, ENV_HC_SITE_NAME, ENV_HC_SITE_ROOT, ENV_HEALTHCHECKS_GROUP, ENV_HEALTHCHECKS_USER, ENV_HEALTHCHECKS_VERSION, ENV_HOME, ENV_HOSTNAME, ENV_OLDPWD, ENV_PATH, ENV_PWD, ENV_SECRET_KEY, ENV_SHLVL, ENV_TERM, ENV_TZ, group_name, here, host_node_name, process_num, program_name in section 'program:prunepings' (file: '/etc/supervisor/supervisord.conf')

For help, use /usr/bin/supervisord -h
```
The image just circles around the same loop.

Any help appreciated.

Thanks in advance.

Rusty.

**Comment by galexrt** [comment]
@Rustymage Post your docker-compose.yaml or `docker run` command.

**Comment by Rustymage** [comment]
`docker run -d --name bitwarden -v /bw-data/:/data/ -p 76:80 -e SIGNUPS_ALLOWED=false -e ADMIN_TOKEN=TOKEN SMTP_HOST=smtp.gmail.com -e SMTP_FROM=ADDRESS@gmail.com -e SMTP_PORT=587 -e SMTP_SSL=true -e SMTP_USERNAME=ADDRESS@gmail.com -e SMTP_PASSWORD=PASSWORD  bitwardenrs/server:latest
`

I use Portainer for management of containers, so I ran the above a few images ago. For this image (broken) and the last several images (working) I download the image and subsequently use the duplicate feature of Portainer to update using the same mount volume to keep the data.

**Comment by swoga** [comment]
Sorry I think my PR broke this.
I think you need to add the `CONTAINER_PRUNE_INTERVAL` environment variable for the image to work.

**Comment by Rustymage** [comment]
I'll check & report back, thanks!

**Comment by galexrt** [comment]
@swoga Let's add it to the `entrypoint.sh` to in the future have all custom env var defaults there.

Are you going to create a PR?

**Comment by swoga** [comment]
@galexrt Yes, I will create a PR

**Comment by galexrt** [comment]
I have finally gotten the time to push a new tag, it should be built soon and available under: `v1.16.0-20201006-124445-270`.

**Comment by Rustymage** [comment]
Hi,

I have used this container and it now won't let me login. 

How can I assist to demonstrate whta might have gone wrong?

Thanks.

**Comment by galexrt** [comment]
@Rustymage You need to register / create an user for that you either need to have working SMTP configured or using the `manage.py` to create a superuser, e.g., https://github.com/galexrt/docker-healthchecks#create-healthchecks-superuser.

**Comment by Rustymage** [comment]
I already have a working configuration and was upgrading so I wouldn't expect to start fresh or create a new user.

Have I misunderstood?

**Comment by galexrt** [comment]
@Rustymage What database are you using? If you are using sqlite, have you used a volume?

**Comment by Rustymage** [comment]
I have used the default sqlite. I have 1 volume:

/data

**Comment by galexrt** [comment]
What is your `docker run` command and / or environment variables? (Redact secrets from them).

If you have used a very very old image version, the env vars are not prefixe with `HC_` anymore, see https://github.com/galexrt/docker-healthchecks#running-the-image for an example `docker run` command.

**Comment by Rustymage** [comment]
I'm afraid to say I don't have my run command as I've not saved it. I use Portainer to manage.

Here's the env variables.
<img width="837" alt="Screenshot 2020-10-09 at 19 13 24" src="https://user-images.githubusercontent.com/19926955/95617683-b9317b80-0a63-11eb-9783-8514960ef85e.png">

**Comment by galexrt** [comment]
Ah as written you need to remove the `HC_` from the environment variables.

**Comment by Rustymage** [comment]
Thanks!

**Comment by Rustymage** [comment]
Just wanted to follow up @galexrt and say thanks for the help. I got it all working on the latest image with data intact.
