### ISSUE TITLE
No E-Mail Notifications will be send on up or down of check but testing the email integration works

### ISSUE THREAD

**Issue by CodeSmolder** [galexrt/docker-healthchecks#42]
Hi,

I am running healthchecks as a daemon using a docker-compose.yml file which looks as follows:
```
version: '3'
services:
  healthchecks:
    image: galexrt/healthchecks:latest
    container_name: healthchecks
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - SQLite:/data
    environment:
      # DB_NAME must be set like this for the /data volume to be used
      # otherwise the SQLite db is lost on container deletion.
      DB_NAME: "/data/hc.sqlite"
      SECRET_KEY: 'secret'
      ALLOWED_HOSTS: 'localhost,hc.example.com'
      DEBUG: "False"
      DEFAULT_FROM_EMAIL: "hc-noreply@hc.example.com"
      USE_PAYMENTS: "False"
      REGISTRATION_OPEN: "False"
      EMAIL_HOST: "mailout.example.com"
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: "user"
      EMAIL_HOST_PASSWORD: "password"
      EMAIL_USE_TLS: "True"
      SITE_ROOT: "https://hc.example.com"
      SITE_NAME: "HCM"
      MASTER_BADGE_LABEL: "HCM"
      PING_ENDPOINT: "https://hc.example.com/ping/"
      TWILIO_ACCOUNT: "None"
      TWILIO_AUTH: "None"
      TWILIO_FROM: "None"
      PD_VENDOR_KEY: "None"
      TRELLO_APP_KEY: "None"
      CONTAINER_PRUNE_INTERVAL: 600
volumes:
  SQLite:
```

E-Mail notifications worked properly but after a few days suddenly no more notification emails (up or down of a check) were sent by healthchecks any more. Docker logs show a traceback which seams to show up on every notification attempt: 

```
2020-10-05 00:47:18,811 INFO success: sendalerts entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 84, in emit
    self.flush()
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 64, in flush
    self.stream.flush()
IOError: [Errno 28] No space left on device
```

I checked the running processes and ```/usr/bin/python3 manage.py sendreports --loop ``` was still running.

Interesting is, that if I test the email integration with the test button manually, the mail will be delivered successfully.

After restarting the docker container everything seems to be working again properly.

Does anyone know what causes the IOError?

**Comment by galexrt** [comment]
Does your machine still enough space? `No space left on device`

Post the `df -h` of your host.

**Comment by CodeSmolder** [comment]
```
[root@x2845532 ~]# df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
devtmpfs         16G       0   16G    0% /dev
tmpfs            16G       0   16G    0% /dev/shm
tmpfs            16G    1,6G   15G   10% /run
tmpfs            16G       0   16G    0% /sys/fs/cgroup
/dev/md1        436G    393G   22G   95% /
/dev/md0        969M    225M  678M   25% /boot
tmpfs           3,2G       0  3,2G    0% /run/user/0
overlay         436G    393G   22G   95% /var/lib/docker/overlay/0baf47a78cc8fb65c06c5dfcc7d08eed1243c2d074ffd41e04ded89d01e93406/merged
```

**Comment by galexrt** [comment]
@CodeSmolder Exec into the container and run `df` there, the `supervisor` program runs healthchecks and such so it probably is related to the low percent of storage available, e.g., different volume / mounts are used for / inside the container.

Make sure quotas and such don't affect the volume(s) and container(s) you have running.

**Comment by galexrt** [comment]
@CodeSmolder Also have you already tried to recreate the container itself? Maybe the container's root fs is full. How long is / was the container running?

**Comment by CodeSmolder** [comment]
> @CodeSmolder Exec into the container and run `df` there, the `supervisor` program runs healthchecks and such so it probably is related to the low percent of storage available, e.g., different volume / mounts are used for / inside the container.
> 
> Make sure quotas and such don't affect the volume(s) and container(s) you have running.

```
root@d5a46a8ff620:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         436G  393G   21G  96% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md1        436G  393G   21G  96% /data
shm              64M     0   64M   0% /dev/shm
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
```

I have not quotas set, so there should be not affect on volume(s) and container(s)

**Comment by CodeSmolder** [comment]
> @CodeSmolder Also have you already tried to recreate the container itself? Maybe the container's root fs is full. How long is / was the container running?

I recreated the container and then it worked again with no problem.

The container was running about a week before when the error occurred.

**Comment by galexrt** [comment]
@CodeSmolder I have pushed a commit to lower the log sizes that supervisord will keep, that may solve the issue for good.

The image tag `v1.17.0-20201019-143145-678` should become available in the next 15-30 minutes.

**Comment by CodeSmolder** [comment]
@galexrt: thank you :)
