### ISSUE TITLE
Environment Variables for settings.py

### ISSUE THREAD

**Issue by Braintelligence** [galexrt/docker-healthchecks#5]
You should allow setting of Telegram for the settings.py via environment variables.

https://github.com/healthchecks/healthchecks/blob/master/hc/settings.py#L156

**Comment by galexrt** [comment]
@Braintelligence You just the variable name and add `HC_` before and add it to the environment variables.

**Comment by Braintelligence** [comment]
Oh sorry, I thought only stuff worked, that was explicitly mentioned in the entrypoint.sh

**Comment by galexrt** [comment]
I may need to add the variables that are "special" cases (integer, arrays) but overall that should work for most config options.

**Comment by Braintelligence** [comment]
Do I need to use string brackets for those variables on the right side?

**Comment by galexrt** [comment]
For string values not, quotes are added around your variable, see https://github.com/galexrt/docker-healthchecks/blob/master/entrypoint.sh#L75

**Comment by Braintelligence** [comment]
What would be the easiest way to check the contents of the settings.py currently? There's no nano or vim available in the container T_T

**Comment by galexrt** [comment]
Use `cat PATH_TO_SETTINGS_PY`, `less` or `more` (depending on which is installed, cat should be installed).

**Comment by Braintelligence** [comment]
Hm, the settings.py seems to be correct but the Telegram Bot doesn't react =/... I can't seem to find any debugging info.

**Comment by Braintelligence** [comment]
Same for mail, actually. I can't see any errors in the container logs but mails aren't being sent.

**Comment by Braintelligence** [comment]
@galexrt I want to set DEBUG = False in the settings.py but you already have DEBUG in there resulting in a server error if I do this by HC_DEBUG = False

**Comment by Braintelligence** [comment]
Also it seems that the settings are just copied at the end of the settings.py ... does this work that way? Theoretically you can overwrite variables by just setting it anew, but this creates a lot of spam in the settings.py

**Comment by Braintelligence** [comment]
Oooooh, wait a second. I think those come from upgrading the container with new environment variables.

**Comment by Braintelligence** [comment]
Did you create the container in such a way, that if it is restarted with new environment variables, it would just put them under the settings.py without checking if they were already set?

**Comment by Braintelligence** [comment]
Yeah, overwriting of the variables works, but it seems you can't do:
`DEBUG = True`
then 
`DEBUG = False`
you get HTTP 500 then.

**Comment by Braintelligence** [comment]
Actually you get HTTP 500 if setting `DEBUG = False` in every case... I need to find out if you can even do runserver without it.

**Comment by Braintelligence** [comment]
More info here:
https://github.com/healthchecks/healthchecks/issues/115#issuecomment-354139539

Maybe we should have this command be invokable by docker, without going into the container.

**Comment by galexrt** [comment]
There is a way to invoke `manage.py` commands through the `entrypoint.sh`, but it isn't documented, could you create a separate issue to document that?

**Comment by Braintelligence** [comment]
Done

**Comment by Braintelligence** [comment]
This is something I might work on in a later PR, if it's ok with you we can keep this open until then.

**Comment by galexrt** [comment]
@Braintelligence Yes, is it okay if I assign this issue to you then?

**Comment by Braintelligence** [comment]
Sure

**Comment by galexrt** [comment]
@Braintelligence Any news on this?

**Comment by galexrt** [comment]
@Braintelligence ping

**Comment by Braintelligence** [comment]
Oh wow, I'm sorry for not reacting to your comments O_O.

I get flooded with GitHub mails so much due to Mailcow, that I missed this entirely.

I just stumbled on this because I moved my healthcheck stack from one server to another. Is this here still a thing?

**Comment by galexrt** [comment]
@Braintelligence Yes, this project is still a thing. I had hoped you work on the PR for this feature as you commented earlier.

What is the status on your side?

**Comment by Braintelligence** [comment]
@galexrt Hey, currently I'm super busy. No free time I'm afraid :(. By "here" I meant the this ticket btw.

**Comment by galexrt** [comment]
Closing as the healthchecks project uses env vars to read its config from.
