### ISSUE TITLE
Add how to invoke manage.py subcommands to the documentation

### ISSUE THREAD

**Issue by Braintelligence** [galexrt/docker-healthchecks#9]
For stuff like this: https://github.com/galexrt/docker-healthchecks/issues/5#issuecomment-354148791
we need to document how to invoke manage.py subcommands with docker.

**Comment by galexrt** [comment]
Is this section good enough https://github.com/galexrt/docker-healthchecks#run-managepy-inside-the-container ?

**Comment by Braintelligence** [comment]
Yeah I think so.
I've seen other docker containers with shorter docker commands. For example I've never seen a `/entrypoint.sh` there before the subcommands. 
Can this be shortened?

**Comment by galexrt** [comment]
@Braintelligence It would be either the "shortcut" `/entrypoint.sh` or `python3 /healthchecks/manage.py` which is even longer.

**Comment by Braintelligence** [comment]
https://github.com/pydanny/cookiecutter-django does it like this: http://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html#run-your-app-with-docker-compose

This should be docker exec commands, from what I know.

I thought maybe we could use a similar structure.

**Comment by galexrt** [comment]
It is a `docker exec`, the `/entrypoint.sh` is from inside the container.
> `docker exec -it CONTAINER_NAME /entrypoint.sh app:managepy YOUR_MANAGE_PY_FLAGS_COMMAND`
https://github.com/galexrt/docker-healthchecks#run-managepy-inside-the-container

What do you mean exactly?

**Comment by Braintelligence** [comment]
I meant a structure like this: `docker-compose -f production.yml run django python manage.py shell`

Reworked for exec.

So exec would look something like
`docker exec -it CONTAINER_NAME python manage.py ARGUMENT`

Is it possible to leave out the entrypoint.sh in the exec invoke and make like a switch-case?
Something like

```python
if $1 == django:
# we know, that we need to run python in django context, for example if virtualenv would be used
    if $2 == python:
    # we know, that we need to use python for the following argument
        if $3 == manage.py
        # we use python as binary for manage.py in the django context and apply $4 as subcommand
```

**Comment by galexrt** [comment]
@Braintelligence That is what the `entrypoint.sh` script does. See https://github.com/galexrt/docker-healthchecks/blob/master/entrypoint.sh#L132-L135 and https://github.com/galexrt/docker-healthchecks/blob/master/entrypoint.sh#L142-L155.

**Comment by Braintelligence** [comment]
This is documented and alright.
